FROM ubuntu:latest 

RUN yum update -y && \
    yum install -y vim nginx && \
    yum clean all

COPY app.sh /usr/local/bin/app.sh

RUN chmod +x /usr/local/bin/app.sh

ENTRYPOINT ["/usr/local/bin/app.sh"]


